name: bwa_moviez
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter: 
  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/AvenirLTStd-Black.otf
        - asset: fonts/AvenirLTStd-Book.otf
        - asset: fonts/AvenirLTStd-Roman.otf
  uses-material-design: true
